######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 28 01:31:47 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += window.h
SOURCES += main.cpp window.cpp
