######################################################################
# Automatically generated by qmake (2.01a) Sat Nov 26 09:35:13 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += ex2.cpp
