######################################################################
# Automatically generated by qmake (2.01a) Sat Mar 18 02:18:09 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += window.h
SOURCES += main.cpp window.cpp
